repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v1.2.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet
      - id: golangci-lint
        args: [--fast]
      - id: go-test

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
